carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

zhangetsu/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
   
    path('',ProductListView.as_view(), name='index'),
    path('usuarios/login/', views.login_view, name='login'),
    path('usuarios/logout/', views.logout_view, name='logout'),
    path('usuarios/register/',views.register, name='register' ),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/',include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        

    </head>
    <body>
         
        {% include 'navbar.html' %}

        <div class="container">
           {% include 'messages.html' %}
            <div class="row mt-4">

                {% block content %}
                {% endblock %}

            </div>
        </div>
    
    </body>
    <script src="https://kit.fontawesome.com/89818270f2.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    
 
</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
<div class="col">
    <h4 class="text-center">{{ message }}</h4>
    {% include 'products/snippets/search.html' %}

    {% include 'products/snippets/list.html'%}
    
</div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message  in messages %}
    <div class="alert {% if  message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
        <button type="button" class="close" data-dismiss="alert">x</button>
        {{ message}}
    </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Zhangetsu</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
      <span class="navbar-toggler-icon"></span>  

    </button>
    <div id="navb" class="navbar-collapse collapse hide">
     
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %}active{% endif %}">
                <a class="nav-link" href="{{ cart }}">
                    Mi Carrito<span class="fas fa-shopping-cart"></span>
                </a>

            </li>


        </ul>


        <ul class="nav navbar-nav ml-auto">

            {% if user.is_authenticated %}

                <!-- acceso sin varaibles-->
                <li class="navbar-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                    <span class="fas fa-sign-in-alt"></span>
                    Logout</a>
    
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %} active {% endif %}">
                    <a href="{{ login }}" class="nav-link">
                    <span class="fas fa-user"></span>
                    Login</a>
                </li>
                    <!--acceso con varaibles-->
                <li class="navbar-item {% if request.path == login %} active {% endif %}">
                    <a href="{{ register }}" class="nav-link">
                    <span class="fas fa-user-plus"></span>
                    Registro</a>

                </li>
            {% endif %}
        </ul>

    </div>


</nav>